#!/usr/bin/perl
# A script used by the authors of FastBit to configure the package.
# Terse comments are provided in hoping they might be instructive for
# configuring the package on other machines.
#
use Env qw(HOME HOSTNAME PWD);
if (! ${HOSTNAME}) {
    $HOSTNAME=`hostname`;
}
print "Configuring on ${HOSTNAME}\n";
if (${HOSTNAME} =~ m/bit\.[lbl.gov|local]/) {
# on a Mac used by a developer, enable maintainer mode, use debug options
    $cmd="./configure --prefix=${HOME}/Darwin/fastbit --enable-maintainer-mode --with-java CC=gcc-mp-4.5 CXX=g++-mp-4.5 CFLAGS='-g -O0 -m64 -Wall' CXXFLAGS='-g -O0 -m64 -Wall'";
}
elsif (${HOSTNAME} =~ m/^data5[.lbl.gov]?$/) {
# on data5, know where is java and where to install, use extra optimization
    $cmd="./configure --enable-xopt --disable-debug --with-java=/software/jdk1.7.0 --prefix=/data/john/Linux/fastbit";
}
elsif (${HOSTNAME} =~ m/^d\w+[.lbl.gov]?$/) {
# on sdm group's linux machines, know where is java and where to install
    $cmd="./configure --enable-xopt --disable-debug --with-java=/software/jdk1.7.0 --prefix=/fastbit/Linux/fastbit";
}
elsif (${HOSTNAME} =~ m/^hopper\w+[.nersc.gov]?$/) {
# on hopper at NERSC, use the default GCC compilers, no debugging # Cray compilers wrappers CC=cc CXX=CC
    print "\nPlease make sure that PrgEnv-gnu is used, for example by executing 'module swap PrgEnv-pgi PrgEnv-gnu'\n\n";
    $cmd="./configure --without-getpwuid CFLAGS='-fPIC -O' CXXFLAGS='-fPIC -O' --without-java --prefix=/project/projectdirs/m1248/hopper/fastbit";
}
elsif (${HOSTNAME} =~ m/^fra\w+[\.nersc\.gov]?$/) {
# on franklin at NERSC, use the default compilers, no debugging
    $cmd="./configure --without-getpwuid --disable-debug --without-java --prefix=/project/projectdirs/m1248/franklin/fastbit";
}
elsif (${HOSTNAME} =~ m/\.nersc\.gov$/) {
# on other NERSC machines, use the default compilers, no debugging
    $cmd="./configure --without-getpwuid --disable-debug --enable-xopt";
}
else { # use all default options on generic linux/unix machines
    $cmd="./configure --prefix=${PWD}";
}
print "$cmd\n\n";
system($cmd);
